#server:
#  port: 9093
#
##I want the application work on eureka server
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#
#spring:
#
#  application:
#    name: USER-SERVICE
#    security:
#      jwt:
#        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#        expiration: 86400000 # a day
#        refresh-token:
#          expiration: 604800000 # 7 days
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/userdb
#    #password: root
#    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver     #driver for mysql connection
#
#  jpa:
#    hibernate:
#      #if there are change on the database it will be updated and not create all the table again
#      ddl-auto: update  #create
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #convert orm language to mysql querry
server:
  port: 9093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: USER-SERVICE


  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
